### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by tomwagner**
Docker configuration for sirius. Just run `docker-compose up` and start sirius for your Little Printer.

### CODE REVIEW

**Comment by joerick** [comment]
Nice one @tomwagner! Happy to merge this. How are you hosting it? We've got a server up at littleprinter.nordprojects.co (that's hosted on Heroku, but with a VPS HTTP reverse proxy so it's the default virtual host on that IP)

**Comment by tomwagner** [comment]
I have VPS with installed docker and reverse proxy gateway (https://github.com/goodservers/docker-gateway). So you can connect any kind of containerised application what you want. All you need is to setup environment variables for gateway (host, port). Disabled https because of not working communication with LittlePrinter bridge. My docker compose configuration:

```
version: '2'

services:
  sirius:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    networks:
     - nginx-proxy
    environment:
     - VIRTUAL_HOST=printer.domain.xxx
     - VIRTUAL_PORT=5000
     - HTTPS_METHOD=nohttps
    env_file:
     - .env

networks:
   nginx-proxy:
       external: true
```

**Comment by joerick** [comment]
Nice one! How much RAM do you need to run those containers?

**Comment by tomwagner** [comment]
nginx ~ 35MB
nginx-gen ~35MB
nginx-letsencrypt ~ 35MB
docker-doctor ~ +130MB (you can disable it, for this scenario is not necessary)
and sirius takes about ~ 88MB

So you can host in some low-cost VPS droplets (if you want find some take a look at https://vpscomp.com/servers) with 512MB RAM. But thanks for this question, it forced me to think about this solution from another side :)

**Comment by joerick** [comment]
that's cool! I might think about running on a 512Mb container using this if my Heroku starts costing money!

**Pull request merged**
