### PR TITLE
Adds CORS support to all endpoints (fixes #3)

### LINKED ISSUE #3: CORS support to allow browser-based web apps to access the API
It would be great to be able to write browser-based web apps that communicate with the API. Currently, this isn't possible because `sirius` doesn't support [CORS (Cross-Origin Resource Sharing)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

The browser's same-origin policy means a web app running at http://my-great-app.com is restricted in what kinds of content is can send to another domain, such as http://littleprinter.nordprojects.co.

`POST` HTTP requests with a `Content-Type` of `text/plain` are allowed by browsers, so printing plaintext works. However, `application/json`, `text/html` and `image/*` are blocked which limits the kinds of web apps that can be created.

The solution is for `sirius` to respond with the correct CORS HTTP headers to tell the browser that it is allowed to make these other types of requests.

You can see a tiny [demo web app](https://codepen.io/andrewnicolaou/pen/drWzep) that tries to send HTML via JSON to the printkey API, but fails due to CORS headers not being present in the API.

### PR DESCRIPTION
**Pull request by andrewn**
As described in #3, enabling Cross-Origin Resource Sharing (CORS) will let browser-based web apps  communicate directly with the API.

This uses the [Flask-CORS](http://flask-cors.corydolphin.com/en/latest/) extension. All routes on the web app are enabled, meaning that web apps will be able to request all the endpoints in the app. If needed, this can be narrowed to only [specific resources or routes](http://flask-cors.corydolphin.com/en/latest/#resource-specific-cors).

### CODE REVIEW

**Comment by joerick** [comment]
Nice! Thanks @andrewn! I'd rather limit it just to the print keys because there are a few other APIs that might be a security hole.

If you get a chance in the next couple days that would be awesome otherwise I'll make the change when I merge it in. :)

**Comment by andrewn** [comment]
Thanks for the feedback @joerick. I've restricted this to everything under `/printkey/`.

Screenshot 2019-04-10 10 11 59

My goal is to build a fully-functional equivalent to your iOS app. I presume this is all possible using the print key API?

**Comment by joerick** [comment]
Sorry for the delay on this! It should be live in the next few minutes.

> My goal is to build a fully-functional equivalent to your iOS app. I presume this is all possible using the print key API?

Yes, the iOS app uses only this API, so you should be able to recreate the app's functionality using just the device key :)

**Comment by andrewn** [comment]
It works! 👍 

message test print

**Comment by joerick** [comment]
Nice one! Is that using the new device.li keys also?

**Comment by andrewn** [comment]
It's using `https://littleprinter.nordprojects.co/printkey/...`. What's device.li?

**Comment by joerick** [comment]
Ah I just added a proxy for that to make the links a bit easier to share - `https://device.li/secretkey1234` now also works :) tbh if you're using it with an API it makes no odds - just curious if the CORS setup still works through that too!

**Comment by joerick** [comment]
Oh, it's a proxy that makes the device keys a little more snappy and sharable - they look like `https://device.li/1234secret1234`. But both should still work - just curious if CORS still works through the new device.li keys

**Comment by andrewn** [comment]
> But both should still work - just curious if CORS still works through the new device.li keys

Sorry for the delay, but yeah, CORS seems to be working with device.li keys. 👌 👍 🎉

**Pull request merged**
